import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { toNairobi, nowNairobi } from '@/lib/timezone';

// CRITICAL FIX: Force Next.js to not cache this API route
export const dynamic = 'force-dynamic';

// GET - Get agent dashboard data
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const agentId = searchParams.get('agentId');

    if (!agentId) {
      return NextResponse.json({ error: 'Agent ID is required' }, { status: 400 });
    }

    // Get agent
    const agent = await prisma.agent.findUnique({
      where: { id: agentId },
    });

    if (!agent) {
      return NextResponse.json({ error: 'Agent not found' }, { status: 404 });
    }

    // Get all vouchers generated by this agent
    const agentBatchPattern = agent.name.toUpperCase().replace(/[^A-Z0-9]/g, '');
    const allVouchers = await prisma.hotspotVoucher.findMany({
      where: {
        batchCode: {
          startsWith: agentBatchPattern,
        },
      },
      include: {
        profile: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    // Filter for sold/used vouchers (ACTIVE or EXPIRED with a firstLoginAt)
    const soldVouchers = allVouchers.filter(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (v: any) => (v.status === 'ACTIVE' || v.status === 'EXPIRED') && v.firstLoginAt
    );

    // Calculate statistics directly from vouchers (Real-time)
    const now = nowNairobi();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const currentMonthSales = soldVouchers.filter((v: any) => {
      const saleDate = toNairobi(v.firstLoginAt!);
      if (!saleDate) return false;
      return (
        saleDate.getMonth() === currentMonth &&
        saleDate.getFullYear() === currentYear
      );
    });

    const stats = {
      currentMonth: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        total: currentMonthSales.reduce((sum: number, v: any) => sum + (v.profile?.resellerFee || 0), 0),
        count: currentMonthSales.length,
      },
      allTime: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        total: soldVouchers.reduce((sum: number, v: any) => sum + (v.profile?.resellerFee || 0), 0),
        count: soldVouchers.length,
      },
      generated: allVouchers.length,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      waiting: allVouchers.filter((v: any) => v.status === 'WAITING').length,
    };

    // Get profiles with agentAccess enabled
    const profiles = await prisma.hotspotProfile.findMany({
      where: {
        agentAccess: true,
        isActive: true,
      },
      orderBy: { name: 'asc' },
    });

    return NextResponse.json({
      agent: {
        id: agent.id,
        name: agent.name,
        phone: agent.phone,
        email: agent.email,
      },
      stats,
      profiles,
      // Include costPrice and resellerFee in each voucher so the frontend can calculate deposits
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      vouchers: allVouchers.map((v: any) => ({
        id: v.id,
        code: v.code,
        batchCode: v.batchCode,
        status: v.status,
        profileName: v.profile?.name || 'Unknown',
        costPrice: v.profile?.costPrice || 0,
        resellerFee: v.profile?.resellerFee || 0,
        firstLoginAt: v.firstLoginAt,
        expiresAt: v.expiresAt,
        createdAt: v.createdAt,
      })),
    });
  } catch (error) {
    console.error('Get agent dashboard error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}